### ISSUE TITLE
Because cubes depends on mockito ^4.1.4 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by VomPom** [RafaelBarbosatec/cube#30]
when I execute "flutter pub get" for the example,  get an error:
Because cubes depends on mockito ^4.1.4 which doesn't match any versions, version solving failed.

flutter doctor:
Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale
    zh-Hans-CN)

**Comment by RafaelBarbosatec** [comment]
Thanks for the issue. 
Do you use any specific version of the mockito?
I'll try to switch to `any` to see if this resolves.

**Comment by RafaelBarbosatec** [comment]
Try use version 0.10.7.

**Comment by RafaelBarbosatec** [comment]
I can't reproduce this problem.
I will be closing the issue. Try to run the latest version, if you see the problem you can reopen the issue.
