### ISSUE TITLE
Readme link 404

### ISSUE THREAD

**Issue by slavi010** [RafaelBarbosatec/cube#41]
Hey,

Just a bad link in the readme.

Maybe fixe
`Example widget test [here](https://github.com/RafaelBarbosatec/cube/blob/master/example/test/widget/cube_test.dart)`
to
`Example widget test [here](https://github.com/RafaelBarbosatec/cube/tree/master/example/test/widget/counter)`

Slavi

**Comment by RafaelBarbosatec** [comment]
Updated
