### ISSUE TITLE
3d object loading issue

### ISSUE THREAD

**Issue by imbryan1999** [RafaelBarbosatec/cube#59]
facing issue while loading obj file [ size around 20mb ] it crashes the apps.
used device [iphone 12 pro] 
[mesh (3).zip](https://github.com/RafaelBarbosatec/cube/files/8761559/mesh.3.zip)

**Comment by RafaelBarbosatec** [comment]
Hi @imbryan1999 !
I guess that you open this issue in wrong repository. 😊
This package is a State manager
